### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a child of <tbody>.

### ISSUE THREAD

**Issue by Howie17** [Howie17/dg-weather#17]
I understand the warning in the title, however, if I remove the div it refers to, then the loop that is inside the div throws a syntax error. I imagine this is really basic, but not having learned from the ground up, leaves me with not knowing how to address the situation or even what to ask in a google search.

Context:  CourseForecast.js returns a table. Within the body, a call is made to DSHourly, which is a function that assigns the data from the forecast to props that are then passed to a function called 'Rows,' that formats it.

```
class DSHourly extends React.Component {
       //Excess code removed
    render() {
        let vHourly = this.props.forecast.hourly;
        
        return(
            <div className="hourly">
                {vHourly && vHourly.data.map((hour, index)=> (           
                    <Row
                        key={index}                                                         // Needed when returning a list of components in a loop
                        attr1={ (new Date(hour.time * 1000).getHours()) <= 12 && (new Date(hour.time * 1000).getHours()) !== 0 ? (new Date(hour.time * 1000).getHours()) : this.get12Hour(hour)}
                        attr2={Math.round(hour.temperature)}                             
                        attr3={Math.round(hour.apparentTemperature)}
                        attr4={Math.round(hour.windSpeed)}
                        attr5={Math.round(hour.precipProbability*100)}
                        attr6={Math.round(hour.precipIntensity)}
                        attr7={hour.humidity}
                        attr8={hour.summary}
                        attr9={ (new Date(hour.time * 1000)).getHours() <= 12 ? "AM" : "PM"}
                    />
                ))}
            </div>
        );
    }
}

function Row(props) {
    return (
            <TableRow>
                <TableRowColumn>{props.attr1}:00 {props.attr9}</TableRowColumn>
                <TableRowColumn>{props.attr8}</TableRowColumn>
                <TableRowColumn>{props.attr2} &#x2109;</TableRowColumn>
                <TableRowColumn>{props.attr3} &#x2109;</TableRowColumn>
                <TableRowColumn>{props.attr4} mph</TableRowColumn>
                <TableRowColumn>{props.attr5 }%</TableRowColumn>
                <TableRowColumn>{props.attr6} (in)</TableRowColumn>
                <TableRowColumn>{Math.round(props.attr7*100)}</TableRowColumn>
            </TableRow>
    );
}
```

**Comment by matthewrobb** [comment]
You have hit one of the most annoying edges of React/JSX... You Cannot return multiple components from render.  The trick I use to make this case work is to change the wrapping div to `<tbody>` and dont use a tbody wherever you currently are.

**Comment by Howie17** [comment]
Moving the Material-UI TableBody component down to wrap the loop in DSHourly throws a different error. Per investigation (https://github.com/callemall/material-ui/issues/3637), its a known issue, with the following work around:

> ok, a workaround is adding static muiName = 'TableBody';(ES6) or statics: { muiName: 'TableBody' }, to your wrapping component.

This has solved the issue, and I have subscribed to the thread as they mentioned refactoring the table component going forward, its been over 6 months with no update, so I'm not holding my breath. :)
